name: AI Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  review:
    uses: pratikpawar009/Test_PR_agent/.github/workflows/review.yml@main
    secrets: inherit